from PyQt5 import QtCore, QtGui, QtWidgets
from Windows.icon_rc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 559)
        MainWindow.setWindowIcon(QtGui.QIcon("Icon\\Logo.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setStyleSheet("QWidget#icon_only_widget{\n"
"    background-color: rgb(23, 25, 27);\n"
"}")
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.change_btn_2 = QtWidgets.QPushButton(self.icon_only_widget)
        self.change_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        self.change_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon/menu.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_btn_2.setIcon(icon)
        self.change_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.change_btn_2.setCheckable(True)
        self.change_btn_2.setObjectName("change_btn_2")
        self.horizontalLayout_3.addWidget(self.change_btn_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.home_btn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon/home-grey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/Icon/home-white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.home_btn_1.setIcon(icon1)
        self.home_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setChecked(True)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)
        self.random_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.random_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.random_btn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon/random-grey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/Icon/randomwhite.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.random_btn_1.setIcon(icon2)
        self.random_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.random_btn_1.setCheckable(True)
        self.random_btn_1.setAutoExclusive(True)
        self.random_btn_1.setObjectName("random_btn_1")
        self.verticalLayout.addWidget(self.random_btn_1)
        self.student_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.student_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.student_btn_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon/student-grey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/Icon/student-white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.student_btn_1.setIcon(icon3)
        self.student_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.student_btn_1.setCheckable(True)
        self.student_btn_1.setAutoExclusive(True)
        self.student_btn_1.setObjectName("student_btn_1")
        self.verticalLayout.addWidget(self.student_btn_1)
        self.advisors_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.advisors_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.advisors_btn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/Icon/group-grey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icon/Icon/group-white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.advisors_btn_1.setIcon(icon4)
        self.advisors_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.advisors_btn_1.setCheckable(True)
        self.advisors_btn_1.setAutoExclusive(True)
        self.advisors_btn_1.setObjectName("advisors_btn_1")
        self.verticalLayout.addWidget(self.advisors_btn_1)
        self.relation_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.relation_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.relation_btn_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/Icon/reference-grey.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/Icon/reference-white.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.relation_btn_1.setIcon(icon5)
        self.relation_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.relation_btn_1.setCheckable(True)
        self.relation_btn_1.setAutoExclusive(True)
        self.relation_btn_1.setObjectName("relation_btn_1")
        self.verticalLayout.addWidget(self.relation_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 375, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.exit_btn_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/Icon/close-window.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(icon6)
        self.exit_btn_1.setIconSize(QtCore.QSize(25, 25))
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)
        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setStyleSheet("QWidget#full_menu_widget{\n"
"    background-color: rgb(23, 25, 27);\n"
"}")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.change_btn_1 = QtWidgets.QPushButton(self.full_menu_widget)
        self.change_btn_1.setMinimumSize(QtCore.QSize(0, 33))
        self.change_btn_1.setText("")
        self.change_btn_1.setIcon(icon)
        self.change_btn_1.setIconSize(QtCore.QSize(18, 18))
        self.change_btn_1.setCheckable(True)
        self.change_btn_1.setObjectName("change_btn_1")
        self.horizontalLayout_2.addWidget(self.change_btn_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.home_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.home_btn_2.setFont(font)
        self.home_btn_2.setIcon(icon1)
        self.home_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setChecked(True)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.verticalLayout_2.addWidget(self.home_btn_2)
        self.random_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.random_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.random_btn_2.setFont(font)
        self.random_btn_2.setIcon(icon2)
        self.random_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.random_btn_2.setCheckable(True)
        self.random_btn_2.setAutoExclusive(True)
        self.random_btn_2.setObjectName("random_btn_2")
        self.verticalLayout_2.addWidget(self.random_btn_2)
        self.student_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.student_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.student_btn_2.setFont(font)
        self.student_btn_2.setIcon(icon3)
        self.student_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.student_btn_2.setCheckable(True)
        self.student_btn_2.setAutoExclusive(True)
        self.student_btn_2.setObjectName("student_btn_2")
        self.verticalLayout_2.addWidget(self.student_btn_2)
        self.advisors_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.advisors_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.advisors_btn_2.setFont(font)
        self.advisors_btn_2.setIcon(icon4)
        self.advisors_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.advisors_btn_2.setCheckable(True)
        self.advisors_btn_2.setAutoExclusive(True)
        self.advisors_btn_2.setObjectName("advisors_btn_2")
        self.verticalLayout_2.addWidget(self.advisors_btn_2)
        self.relation_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.relation_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.relation_btn_2.setFont(font)
        self.relation_btn_2.setIcon(icon5)
        self.relation_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.relation_btn_2.setCheckable(True)
        self.relation_btn_2.setAutoExclusive(True)
        self.relation_btn_2.setObjectName("relation_btn_2")
        self.verticalLayout_2.addWidget(self.relation_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exit_btn_2.setFont(font)
        self.exit_btn_2.setIcon(icon6)
        self.exit_btn_2.setIconSize(QtCore.QSize(18, 18))
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.action_groupbox = QtWidgets.QGroupBox(self.page)
        self.action_groupbox.setObjectName("action_groupbox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.action_groupbox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_18 = QtWidgets.QLabel(self.action_groupbox)
        self.label_18.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 1, 0, 1, 1)
        self.action_cb = QtWidgets.QComboBox(self.action_groupbox)
        self.action_cb.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_cb.setFont(font)
        self.action_cb.setObjectName("action_cb")
        self.action_cb.addItem("")
        self.action_cb.addItem("")
        self.action_cb.addItem("")
        self.action_cb.addItem("")
        self.action_cb.addItem("")
        self.action_cb.addItem("")
        self.gridLayout_15.addWidget(self.action_cb, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem2, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.choose_3 = QtWidgets.QComboBox(self.action_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose_3.setFont(font)
        self.choose_3.setObjectName("choose_3")
        self.choose_3.addItem("")
        self.choose_3.addItem("")
        self.horizontalLayout_4.addWidget(self.choose_3)
        self.choose_4 = QtWidgets.QComboBox(self.action_groupbox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose_4.setFont(font)
        self.choose_4.setObjectName("choose_4")
        self.horizontalLayout_4.addWidget(self.choose_4)
        self.gridLayout_15.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.result_lbl = QtWidgets.QTextBrowser(self.action_groupbox)
        self.result_lbl.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.result_lbl.setFont(font)
        self.result_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lbl.setObjectName("result_lbl")
        self.gridLayout_15.addWidget(self.result_lbl, 7, 0, 1, 2)
        self.result_btn = QtWidgets.QPushButton(self.action_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_btn.setFont(font)
        self.result_btn.setObjectName("result_btn")
        self.gridLayout_15.addWidget(self.result_btn, 5, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem3, 2, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 6, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 4, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem6, 8, 0, 1, 1)
        self.gridLayout_2.addWidget(self.action_groupbox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.random_groupbox = QtWidgets.QGroupBox(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.random_groupbox.setFont(font)
        self.random_groupbox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.random_groupbox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.student_dsb = QtWidgets.QDoubleSpinBox(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.student_dsb.setFont(font)
        self.student_dsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.student_dsb.setDecimals(0)
        self.student_dsb.setMaximum(10000.0)
        self.student_dsb.setObjectName("student_dsb")
        self.gridLayout_9.addWidget(self.student_dsb, 3, 1, 1, 1)
        self.advisors_dsb = QtWidgets.QDoubleSpinBox(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.advisors_dsb.setFont(font)
        self.advisors_dsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.advisors_dsb.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.advisors_dsb.setDecimals(0)
        self.advisors_dsb.setMaximum(1000.0)
        self.advisors_dsb.setObjectName("advisors_dsb")
        self.gridLayout_9.addWidget(self.advisors_dsb, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.random_groupbox)
        self.label.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem7, 12, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.random_groupbox)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.random_groupbox)
        self.label_3.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 5, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 4, 0, 1, 2)
        self.random_db_pb = QtWidgets.QPushButton(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.random_db_pb.setFont(font)
        self.random_db_pb.setObjectName("random_db_pb")
        self.gridLayout_9.addWidget(self.random_db_pb, 9, 0, 1, 2)
        self.region_cb = QtWidgets.QComboBox(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.region_cb.setFont(font)
        self.region_cb.setObjectName("region_cb")
        self.gridLayout_9.addWidget(self.region_cb, 1, 1, 1, 1)
        self.random_progressbar = QtWidgets.QProgressBar(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.random_progressbar.setFont(font)
        self.random_progressbar.setProperty("value", 0)
        self.random_progressbar.setAlignment(QtCore.Qt.AlignCenter)
        self.random_progressbar.setObjectName("random_progressbar")
        self.gridLayout_9.addWidget(self.random_progressbar, 11, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 2, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 10, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 6, 0, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem12, 0, 0, 1, 2)
        self.relation_dsb = QtWidgets.QDoubleSpinBox(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.relation_dsb.setFont(font)
        self.relation_dsb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.relation_dsb.setDecimals(0)
        self.relation_dsb.setMaximum(5000.0)
        self.relation_dsb.setObjectName("doubleSpinBox")
        self.gridLayout_9.addWidget(self.relation_dsb, 7, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.random_groupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 7, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem13, 8, 0, 1, 2)
        self.gridLayout_3.addWidget(self.random_groupbox, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.st_ad_groupbox = QtWidgets.QGroupBox(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.st_ad_groupbox.setFont(font)
        self.st_ad_groupbox.setObjectName("st_ad_groupbox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.st_ad_groupbox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget = QtWidgets.QTableWidget(self.st_ad_groupbox)
        self.tableWidget.setMinimumSize(QtCore.QSize(550, 300))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_10.addWidget(self.tableWidget, 5, 0, 3, 2)
        self.frame = QtWidgets.QFrame(self.st_ad_groupbox)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.delete_button = QtWidgets.QPushButton(self.frame)
        self.delete_button.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_button.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/Icon/delete.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon7)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout_6.addWidget(self.delete_button)
        self.save_button = QtWidgets.QPushButton(self.frame)
        self.save_button.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_button.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/Icon/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon8)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_6.addWidget(self.save_button)
        self.gridLayout_10.addWidget(self.frame, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.st_ad_groupbox)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 2, 0, 1, 1)
        self.age_input = QtWidgets.QLineEdit(self.st_ad_groupbox)
        self.age_input.setMinimumSize(QtCore.QSize(0, 25))
        self.age_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.age_input.setFont(font)
        self.age_input.setObjectName("age_input")
        self.gridLayout_10.addWidget(self.age_input, 2, 1, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.st_ad_groupbox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_button.setFont(font)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/Icon/search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon9)
        self.search_button.setIconSize(QtCore.QSize(14, 14))
        self.search_button.setObjectName("search_button")
        self.gridLayout_10.addWidget(self.search_button, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.st_ad_groupbox)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.st_ad_groupbox)
        self.name_input.setMinimumSize(QtCore.QSize(0, 25))
        self.name_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_input.setFont(font)
        self.name_input.setObjectName("name_input")
        self.gridLayout_10.addWidget(self.name_input, 0, 1, 1, 1)
        self.add_button = QtWidgets.QPushButton(self.st_ad_groupbox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_button.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/Icon/add.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon10)
        self.add_button.setObjectName("add_button")
        self.gridLayout_10.addWidget(self.add_button, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.st_ad_groupbox)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.surname_input = QtWidgets.QLineEdit(self.st_ad_groupbox)
        self.surname_input.setMinimumSize(QtCore.QSize(0, 25))
        self.surname_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.surname_input.setFont(font)
        self.surname_input.setObjectName("surname_input")
        self.gridLayout_10.addWidget(self.surname_input, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem14, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.st_ad_groupbox, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.relation_groupbox = QtWidgets.QGroupBox(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.relation_groupbox.setFont(font)
        self.relation_groupbox.setObjectName("relation_groupbox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.relation_groupbox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem15, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.relation_groupbox)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.delete_button_2 = QtWidgets.QPushButton(self.frame_2)
        self.delete_button_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_button_2.setFont(font)
        self.delete_button_2.setIcon(icon7)
        self.delete_button_2.setObjectName("delete_button_2")
        self.verticalLayout_7.addWidget(self.delete_button_2)
        self.gridLayout_11.addWidget(self.frame_2, 5, 2, 1, 1)
        self.student_id = QtWidgets.QLineEdit(self.relation_groupbox)
        self.student_id.setMinimumSize(QtCore.QSize(0, 25))
        self.student_id.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.student_id.setFont(font)
        self.student_id.setObjectName("student_id")
        self.gridLayout_11.addWidget(self.student_id, 0, 1, 1, 1)
        self.add_button_2 = QtWidgets.QPushButton(self.relation_groupbox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_button_2.setFont(font)
        self.add_button_2.setIcon(icon10)
        self.add_button_2.setObjectName("add_button_2")
        self.gridLayout_11.addWidget(self.add_button_2, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.relation_groupbox)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.relation_groupbox)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 0, 1, 1)
        self.advisor_id_input = QtWidgets.QLineEdit(self.relation_groupbox)
        self.advisor_id_input.setMinimumSize(QtCore.QSize(0, 25))
        self.advisor_id_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.advisor_id_input.setFont(font)
        self.advisor_id_input.setObjectName("advisor_id_input")
        self.gridLayout_11.addWidget(self.advisor_id_input, 1, 1, 1, 1)
        self.search_button_2 = QtWidgets.QPushButton(self.relation_groupbox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_button_2.setFont(font)
        self.search_button_2.setIcon(icon9)
        self.search_button_2.setObjectName("search_button_2")
        self.gridLayout_11.addWidget(self.search_button_2, 1, 2, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.relation_groupbox)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(550, 396))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.gridLayout_11.addWidget(self.tableWidget_2, 4, 0, 2, 2)
        self.gridLayout_5.addWidget(self.relation_groupbox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.change_btn_2.setStyleSheet("background-color: rgb(68, 138, 255)")
        self.change_btn_1.setStyleSheet("background-color: rgb(68, 138, 255)")
        self.choose_4.hide()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.icon_only_widget.hide()
        column_widths = [60, 100, 120, 80]
        for col, width in enumerate(column_widths):
                self.tableWidget.setColumnWidth(col, width)
        column_widths = [120, 120]
        for col, width in enumerate(column_widths):
                self.tableWidget_2.setColumnWidth(col, width)
        self.change_btn_1.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn_1.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.home_btn_1.toggled['bool'].connect(self.home_btn_2.setChecked) # type: ignore
        self.student_btn_1.toggled['bool'].connect(self.student_btn_2.setChecked) # type: ignore
        self.relation_btn_1.toggled['bool'].connect(self.relation_btn_2.setChecked) # type: ignore
        self.random_btn_1.toggled['bool'].connect(self.random_btn_2.setChecked) # type: ignore
        self.advisors_btn_1.toggled['bool'].connect(self.advisors_btn_2.setChecked) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.home_btn_1.setChecked) # type: ignore
        self.student_btn_2.toggled['bool'].connect(self.student_btn_1.setChecked) # type: ignore
        self.relation_btn_2.toggled['bool'].connect(self.relation_btn_1.setChecked) # type: ignore
        self.random_btn_2.toggled['bool'].connect(self.random_btn_1.setChecked) # type: ignore
        self.advisors_btn_2.toggled['bool'].connect(self.advisors_btn_1.setChecked) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        self.change_btn_2.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn_2.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore
        self.change_btn_1.toggled['bool'].connect(self.change_btn_2.setChecked) # type: ignore
        self.change_btn_2.toggled['bool'].connect(self.change_btn_1.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Relation DB"))
        self.home_btn_2.setText(_translate("MainWindow", "Home"))
        self.random_btn_2.setText(_translate("MainWindow", "Random"))
        self.student_btn_2.setText(_translate("MainWindow", "Student"))
        self.advisors_btn_2.setText(_translate("MainWindow", "Advisors"))
        self.relation_btn_2.setText(_translate("MainWindow", "Relation"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))
        self.action_groupbox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_18.setText(_translate("MainWindow", "Choose:"))
        self.action_cb.setItemText(0, _translate("MainWindow", "List of advisors indicating the number of their students."))
        self.action_cb.setItemText(1, _translate("MainWindow", "List of students indicating the number of their advisors."))
        self.action_cb.setItemText(2, _translate("MainWindow", "Adviser with the maximum number of students."))
        self.action_cb.setItemText(3, _translate("MainWindow", "Adviser with a minimum number of students."))
        self.action_cb.setItemText(4, _translate("MainWindow", "A student with the maximum number of advisers."))
        self.action_cb.setItemText(5, _translate("MainWindow", "A student with a minimum number of advisers."))
        self.choose_3.setItemText(0, _translate("MainWindow", "Ascending."))
        self.choose_3.setItemText(1, _translate("MainWindow", "Descending."))
        self.result_btn.setText(_translate("MainWindow", "Result"))
        self.random_groupbox.setTitle(_translate("MainWindow", "Random data for DB"))
        self.label.setText(_translate("MainWindow", "Region:"))
        self.label_2.setText(_translate("MainWindow", "Student Amount:"))
        self.label_3.setText(_translate("MainWindow", "Advisors Amount:"))
        self.random_db_pb.setText(_translate("MainWindow", "Generate"))
        self.label_4.setText(_translate("MainWindow", "Relation Amount:"))
        self.st_ad_groupbox.setTitle(_translate("MainWindow", "Student DB"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SURNAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "Age:"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Surname:"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.label_11.setText(_translate("MainWindow", "Name:"))
        self.relation_groupbox.setTitle(_translate("MainWindow", "Relation DB"))
        self.delete_button_2.setText(_translate("MainWindow", "Delete"))
        self.add_button_2.setText(_translate("MainWindow", "Add"))
        self.label_12.setText(_translate("MainWindow", "AdvisorID"))
        self.label_7.setText(_translate("MainWindow", "StudentID"))
        self.search_button_2.setText(_translate("MainWindow", "Search"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "StudentID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AdvisorID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
